# Redirect all traffic to HTTPS
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name ai.hiube.ch;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Using upstream enables us to restart ollama without restarting the nginx
upstream ollama {
    server host.docker.internal:11434;
}

server {
    listen 43434 ssl;
    listen [::]:43434 ssl;

    server_name ai.hiube.ch;

    include /config/nginx/ssl.conf;

    location / {
        auth_basic "Restricted";
        auth_basic_user_file /config/nginx/.htpasswd;

        proxy_pass http://ollama;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}
