import shutil
from pathlib import Path
import subprocess
import signal
import os

DEFAULT_DHCP = {
    "range_start": "10.0.0.10",
    "range_end": "10.0.4.14",  # 1024 addresses
    "lease_time": "12h",
}


def _dnsmasq_bin() -> str:
    # Resolve binary robustly on minimal systems (dnsmasq often lives in /usr/sbin)
    return shutil.which("dnsmasq") or "/usr/sbin/dnsmasq"


def run(args: dict) -> dict:
    # required arguments
    interface = args["interface"]

    dhcp = DEFAULT_DHCP.copy()

    # runtime paths
    run_dir = Path("/tmp/nsak/dnsmasq")
    run_dir.mkdir(parents=True, exist_ok=True)

    conf_path = run_dir / "dnsmasq.conf"
    leases_path = run_dir / "dnsmasq.leases"

    # render simple config, dhcp_lease_file keeps a db of leases it has assigned
    conf = f"""
# generated by nsak dnsmasq drill
interface={interface}
bind-interfaces
listen-address=10.0.0.1
dhcp_range={dhcp['range_start']},{dhcp['range_end']},{dhcp['lease_time']}
dhcp_lease_file={leases_path}
log-dhcp
"""

    conf_path.write_text(conf.strip() + "\n")

    dnsmasq = _dnsmasq_bin()
    if not Path(dnsmasq).exists():
        raise RuntimeError("dnsmasq binary not found at PATH or /usr/sbin/dnsmasq")

    # start process
    proc = subprocess.Popen(
        [
            dnsmasq,
            f"--conf-file={conf_path}",
            "--no-daemon",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    return {
        "pid": proc.pid,
        "conf_path": str(conf_path),
        "leases_path": str(leases_path),
    }


def cleanup(result: dict) -> None:
    pid = result.get("pid")
    if not pid:
        return

    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
